#服务端口
server:
  port: 8002
#服务名
spring:
  application:
      name: service-oss
#环境设置：dev、test、prod
  profiles:
      active: dev
#阿里云 OSS
#不同的服务器，地址不同
#bucket可以在控制台创建，也可以使用java代码创建
aliyun:
  oss:
    file:
      endpoint: oss-cn-chengdu.aliyuncs.com
      keyid: LTAIJ8HeSlbRj07j
      keysecret: UzvEJHdgrPEKcAdStWWlpYQ2RgN119
      bucketname: edu-guli-zx
